#!/usr/bin/env python
# coding=utf-8


import argparse
import urllib.parse as parse


def main(input_str):
    return parse.quote(input_str)


if __name__ == '__main__':
    help_msg = u"""
        usage: urlencode xxxxxxxxx
    """
    parser = argparse.ArgumentParser(description=help_msg)
    parser.add_argument('url')
    args = parser.parse_args()
    print(main(args.url))
